name: FirstSpawnRTP
version: '${version}'
author: "Jessee_Dantonio"
depend:
  - LuckPerms

permissions:
  rtp.reset:
    description: Permission to reset database
    default: op
  rtp.reload:
    description: Permission to reload config
    default: op
  rtp.other:
    description: Permission to teleport another player
    default: op

commands:
  rtp:
    description: RTP command
    usage: /fsprtp
    defaults: true
    aliases: [rtp]

main: fr.jessee.firstSpawnRTP.FirstSpawnRTP
api-version: '26.1.2'
load: POSTWORLD
